In [2]:
import pandas as pd

Read a CSV file into a Pandas DataFrame and display the first few rows.

In [3]:
df = pd.read_csv("/home/shuruyi/Documents/git/machine-learning/pandas/sample_file.csv")
df.head()

,ZIP_CODE,COUNTY,DOMAIN_NAME,ZIP_CODE.1,STREET_NAME,LATITUDE,STREET_ADDRESS,STATE
0,10108-9702,Borders,rosalyn.com,14649-0404,Riley Cliff,-21.2197,20530 Adaline Spurs,Georgia
1,44432-2684,Berkshire,devin.info,13405,Johan Village,53.0743,9482 Sporer Keys,Maryland
2,61808-2074,Bedfordshire,garret.name,56865-6328,Alanis Inlet,-28.6071,95859 Langosh Cliffs,Massachusetts
3,17550-8516,Bedfordshire,laverne.biz,52518-3593,Waylon Orchard,-21.0279,52675 Damon Heights,Rhode Island
4,38743,Buckinghamshire,karolann.org,41460,Wunsch Divide,-56.7542,06510 Jerde Village,Maine

Create a new column in the DataFrame by combining values from existing columns.

In [4]:
df = df.assign(FULL_ADDRESS=lambda x: x['STREET_NAME'] + ", " + x["STATE"])
df

,ZIP_CODE,COUNTY,DOMAIN_NAME,ZIP_CODE.1,STREET_NAME,LATITUDE,STREET_ADDRESS,STATE,FULL_ADDRESS
0,10108-9702,Borders,rosalyn.com,14649-0404,Riley Cliff,-21.2197,20530 Adaline Spurs,Georgia,"Riley Cliff, Georgia"
1,44432-2684,Berkshire,devin.info,13405,Johan Village,53.0743,9482 Sporer Keys,Maryland,"Johan Village, Maryland"
2,61808-2074,Bedfordshire,garret.name,56865-6328,Alanis Inlet,-28.6071,95859 Langosh Cliffs,Massachusetts,"Alanis Inlet, Massachusetts"
3,17550-8516,Bedfordshire,laverne.biz,52518-3593,Waylon Orchard,-21.0279,52675 Damon Heights,Rhode Island,"Waylon Orchard, Rhode Island"
4,38743,Buckinghamshire,karolann.org,41460,Wunsch Divide,-56.7542,06510 Jerde Village,Maine,"Wunsch Divide, Maine"
...,...,...,...,...,...,...,...,...,...
995,08036-7563,Bedfordshire,edmond.info,88156-2554,Moen Village,-24.3313,88945 Hortense Plaza,Georgia,"Moen Village, Georgia"
996,63660,Berkshire,genevieve.com,68079-6548,Magnolia Motorway,-50.1882,6989 Zena Walks,Wyoming,"Magnolia Motorway, Wyoming"
997,50921,Borders,lelah.net,63427,Nienow Park,14.5610,78912 Rogahn Hills,Missouri,"Nienow Park, Missouri"
998,56151,Cambridgeshire,ivy.biz,41172,Hickle Views,50.7896,2930 Murray Creek,Rhode Island,"Hickle Views, Rhode Island"
999,44594,Buckinghamshire,vilma.biz,80113-7668,Cathy Inlet,2.8125,3669 Kreiger Shores,Idaho,"Cathy Inlet, Idaho"

Filter the DataFrame to select rows based on a condition (e.g., values greater than a certain threshold).

In [5]:
df_filtered = df[df["LATITUDE"] > 5]
df_filtered

,ZIP_CODE,COUNTY,DOMAIN_NAME,ZIP_CODE.1,STREET_NAME,LATITUDE,STREET_ADDRESS,STATE,FULL_ADDRESS
1,44432-2684,Berkshire,devin.info,13405,Johan Village,53.0743,9482 Sporer Keys,Maryland,"Johan Village, Maryland"
5,82714,Buckinghamshire,garland.name,42180-4334,Ellie Port,37.1570,0617 Witting Trail,Nebraska,"Ellie Port, Nebraska"
7,68947,Cambridgeshire,madge.biz,74681,Fahey Springs,64.4014,67707 Uriah Bypass,Delaware,"Fahey Springs, Delaware"
9,52055-5653,Berkshire,malika.com,60830,Jerry Wall,77.5938,39286 Casimir Tunnel,Colorado,"Jerry Wall, Colorado"
12,54867-2265,Bedfordshire,gaetano.net,58374,Zieme Viaduct,86.0457,1204 Sipes Lodge,Alabama,"Zieme Viaduct, Alabama"
...,...,...,...,...,...,...,...,...,...
988,08984-1290,Buckinghamshire,wilburn.biz,63798,Hamill Corner,50.2552,249 Amiya Rest,Georgia,"Hamill Corner, Georgia"
990,89199-8070,Buckinghamshire,carmela.org,65844,Boyle Locks,84.7763,47801 Patrick Branch,North Carolina,"Boyle Locks, North Carolina"
993,77030-7966,Avon,edgar.net,89455,Gail Island,11.7932,14546 Crooks Green,Montana,"Gail Island, Montana"
997,50921,Borders,lelah.net,63427,Nienow Park,14.5610,78912 Rogahn Hills,Missouri,"Nienow Park, Missouri"
998,56151,Cambridgeshire,ivy.biz,41172,Hickle Views,50.7896,2930 Murray Creek,Rhode Island,"Hickle Views, Rhode Island"

Sort the DataFrame based on a specific column in ascending order.

In [6]:
df_ascending = df.sort_values(by=["LATITUDE"], ascending=True)
df_ascending

,ZIP_CODE,COUNTY,DOMAIN_NAME,ZIP_CODE.1,STREET_NAME,LATITUDE,STREET_ADDRESS,STATE,FULL_ADDRESS
309,63990,Buckinghamshire,jonas.name,39635,Rowe Turnpike,-89.9878,571 Lisa Crest,Michigan,"Rowe Turnpike, Michigan"
916,20727-7291,Buckinghamshire,elliot.net,01549,Mertz Overpass,-89.9627,115 Davis Glen,Montana,"Mertz Overpass, Montana"
263,00752,Bedfordshire,jake.info,54254,Purdy Row,-89.6951,107 Blanda Motorway,Montana,"Purdy Row, Montana"
720,38979,Berkshire,dashawn.net,49505-0730,Lucienne Islands,-89.5857,797 Sebastian Springs,Pennsylvania,"Lucienne Islands, Pennsylvania"
514,48076,Berkshire,giovanni.net,36114,Devonte Forest,-89.5744,7651 Jeffry Gateway,Florida,"Devonte Forest, Florida"
...,...,...,...,...,...,...,...,...,...
577,76487-3392,Berkshire,harry.biz,56004,Weissnat Drives,88.8392,2887 Earl Courts,Illinois,"Weissnat Drives, Illinois"
836,63724-3290,Berkshire,xander.net,66806-5996,Windler Well,89.1131,28271 Denesik Port,Colorado,"Windler Well, Colorado"
454,84618-0605,Berkshire,verda.com,09021-9631,Metz Forest,89.1838,54510 Hegmann Vista,Missouri,"Metz Forest, Missouri"
984,74231,Berkshire,arely.com,50695,Ryley Ramp,89.6525,4802 Roob Street,New Mexico,"Ryley Ramp, New Mexico"
82,64550-1921,Avon,jayde.org,36098,Kathlyn Points,89.9378,3199 Hackett Glens,Rhode Island,"Kathlyn Points, Rhode Island"

Calculate summary statistics (mean, median, min, max) for numerical columns in the DataFrame.

In [7]:
df.groupby("STATE")[["LATITUDE"]].agg(["mean", "median", "min", "max"])

                 LATITUDE
                     mean    median      min      max
STATE
Alabama         21.009478  29.61250 -57.0610  86.0457
Alaska         -12.226494 -15.24080 -86.5038  81.4457
Arizona          5.603243   6.80790 -57.8328  85.2789
Arkansas        13.164246  30.27425 -83.5196  79.8251
California       2.776886   5.14360 -84.2682  80.2147
Colorado        15.632100  17.35700 -77.9280  89.1131
Connecticut      3.806175  -0.52965 -67.8630  81.8006
Delaware        -3.134689  20.05050 -81.8598  80.1619
Florida          0.663327   9.88480 -89.5744  82.7545
Georgia         -6.994287 -10.47220 -87.0834  82.4414
Hawaii          20.065267  25.73060 -82.1296  80.4039
Idaho           12.984904   6.46745 -75.2156  82.8633
Illinois        -4.055500  -4.61045 -82.6012  88.8392
Indiana         17.350109  56.11730 -64.0974  84.2058
Iowa            -7.070922 -15.12995 -73.9331  88.0359
Kansas          -2.698100  12.44780 -89.3322  48.6622
Kentucky        20.574794  25.87130 -67.6212  82.6437
Louisiana        4.061313  27.97590 -86.6240  75.3911
Maine           18.367100  36.03620 -88.7873  77.1679
Maryland       -10.390321  -2.85690 -77.8493  53.2767
Massachusetts    9.297986  -0.71170 -75.5488  88.2390
Michigan         4.799808  30.35110 -89.9878  82.0906
Minnesota       -0.368233 -14.17690 -56.7850  74.5948
Mississippi      1.995567   6.72830 -88.9206  87.3591
Missouri        14.909974  14.56100 -72.2587  89.1838
Montana        -13.436313  -6.24630 -89.9627  87.0064
Nebraska        10.755657   3.75300 -71.0323  88.4202
Nevada          -4.006170  -8.14130 -78.5849  86.8049
New Hampshire    7.277413  20.21900 -85.9853  81.2452
New Jersey      -7.197435  10.00610 -85.3689  78.7869
New Mexico      -4.844025  -6.72425 -86.9503  89.6525
New York         8.708600   4.92125 -84.5168  85.2292
North Carolina   8.119540   5.56375 -58.0874  85.0235
North Dakota    -0.664624  -4.42640 -72.8925  80.5072
Ohio             2.874911   1.53750 -73.4136  83.6498
Oklahoma         4.000006  17.82530 -84.7066  85.6249
Oregon          -8.076933  -0.22820 -80.8239  66.5080
Pennsylvania   -19.441200 -15.10600 -89.5857  70.4847
Rhode Island    14.995461  11.77110 -73.5943  89.9378
South Carolina -12.390363  -6.20950 -82.1103  85.5251
South Dakota     5.414252   4.73650 -88.6039  84.6442
Tennessee       -0.190689 -19.42520 -74.2288  78.1430
Texas          -10.515105  -9.28490 -81.7340  79.4494
Utah            -1.388493   4.52370 -81.6135  83.5668
Vermont        -18.543700 -35.24420 -88.9536  88.2157
Virginia        -6.099479 -11.71390 -84.7505  86.0152
Washington      -3.713959  -1.49920 -75.0673  85.8293
West Virginia    0.787367  -7.44150 -65.0554  61.2228
Wisconsin        0.864500  -2.74540 -77.5478  88.6673
Wyoming         -4.326242  -8.09310 -82.9007  84.8025

Group the DataFrame by a categorical column and calculate aggregate functions (e.g., sum, mean) for each group.

In [11]:
df.groupby("COUNTY")[["LATITUDE"]].agg(["mean", "sum", "median", "min", "max"])

                 LATITUDE
                     mean        sum   median      min      max
COUNTY
Avon             0.602858   102.4858  2.48545 -86.5038  89.9378
Bedfordshire     3.278483   557.3421  2.18635 -89.6951  88.4202
Berkshire       -1.171786  -199.2036 -2.71510 -89.5857  89.6525
Borders          0.377361    66.0381  3.06190 -89.3322  87.0064
Buckinghamshire  3.299171   527.8674  5.03180 -89.9878  88.6673
Cambridgeshire   7.190428  1114.5164  9.88480 -86.3413  87.4442

Merge two DataFrames based on a common column.

In [12]:
df_merged = df.merge(df_ascending, on="ZIP_CODE")
df_merged

,ZIP_CODE,COUNTY_x,DOMAIN_NAME_x,ZIP_CODE.1_x,STREET_NAME_x,LATITUDE_x,STREET_ADDRESS_x,STATE_x,FULL_ADDRESS_x,COUNTY_y,DOMAIN_NAME_y,ZIP_CODE.1_y,STREET_NAME_y,LATITUDE_y,STREET_ADDRESS_y,STATE_y,FULL_ADDRESS_y
0,10108-9702,Borders,rosalyn.com,14649-0404,Riley Cliff,-21.2197,20530 Adaline Spurs,Georgia,"Riley Cliff, Georgia",Borders,rosalyn.com,14649-0404,Riley Cliff,-21.2197,20530 Adaline Spurs,Georgia,"Riley Cliff, Georgia"
1,44432-2684,Berkshire,devin.info,13405,Johan Village,53.0743,9482 Sporer Keys,Maryland,"Johan Village, Maryland",Berkshire,devin.info,13405,Johan Village,53.0743,9482 Sporer Keys,Maryland,"Johan Village, Maryland"
2,61808-2074,Bedfordshire,garret.name,56865-6328,Alanis Inlet,-28.6071,95859 Langosh Cliffs,Massachusetts,"Alanis Inlet, Massachusetts",Bedfordshire,garret.name,56865-6328,Alanis Inlet,-28.6071,95859 Langosh Cliffs,Massachusetts,"Alanis Inlet, Massachusetts"
3,17550-8516,Bedfordshire,laverne.biz,52518-3593,Waylon Orchard,-21.0279,52675 Damon Heights,Rhode Island,"Waylon Orchard, Rhode Island",Bedfordshire,laverne.biz,52518-3593,Waylon Orchard,-21.0279,52675 Damon Heights,Rhode Island,"Waylon Orchard, Rhode Island"
4,38743,Buckinghamshire,karolann.org,41460,Wunsch Divide,-56.7542,06510 Jerde Village,Maine,"Wunsch Divide, Maine",Buckinghamshire,karolann.org,41460,Wunsch Divide,-56.7542,06510 Jerde Village,Maine,"Wunsch Divide, Maine"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
997,08036-7563,Bedfordshire,edmond.info,88156-2554,Moen Village,-24.3313,88945 Hortense Plaza,Georgia,"Moen Village, Georgia",Bedfordshire,edmond.info,88156-2554,Moen Village,-24.3313,88945 Hortense Plaza,Georgia,"Moen Village, Georgia"
998,63660,Berkshire,genevieve.com,68079-6548,Magnolia Motorway,-50.1882,6989 Zena Walks,Wyoming,"Magnolia Motorway, Wyoming",Berkshire,genevieve.com,68079-6548,Magnolia Motorway,-50.1882,6989 Zena Walks,Wyoming,"Magnolia Motorway, Wyoming"
999,50921,Borders,lelah.net,63427,Nienow Park,14.5610,78912 Rogahn Hills,Missouri,"Nienow Park, Missouri",Borders,lelah.net,63427,Nienow Park,14.5610,78912 Rogahn Hills,Missouri,"Nienow Park, Missouri"
1000,56151,Cambridgeshire,ivy.biz,41172,Hickle Views,50.7896,2930 Murray Creek,Rhode Island,"Hickle Views, Rhode Island",Cambridgeshire,ivy.biz,41172,Hickle Views,50.7896,2930 Murray Creek,Rhode Island,"Hickle Views, Rhode Island"
1001,44594,Buckinghamshire,vilma.biz,80113-7668,Cathy Inlet,2.8125,3669 Kreiger Shores,Idaho,"Cathy Inlet, Idaho",Buckinghamshire,vilma.biz,80113-7668,Cathy Inlet,2.8125,3669 Kreiger Shores,Idaho,"Cathy Inlet, Idaho"

Remove duplicate rows from the DataFrame.

In [13]:
df.drop_duplicates()
df

,ZIP_CODE,COUNTY,DOMAIN_NAME,ZIP_CODE.1,STREET_NAME,LATITUDE,STREET_ADDRESS,STATE,FULL_ADDRESS
0,10108-9702,Borders,rosalyn.com,14649-0404,Riley Cliff,-21.2197,20530 Adaline Spurs,Georgia,"Riley Cliff, Georgia"
1,44432-2684,Berkshire,devin.info,13405,Johan Village,53.0743,9482 Sporer Keys,Maryland,"Johan Village, Maryland"
2,61808-2074,Bedfordshire,garret.name,56865-6328,Alanis Inlet,-28.6071,95859 Langosh Cliffs,Massachusetts,"Alanis Inlet, Massachusetts"
3,17550-8516,Bedfordshire,laverne.biz,52518-3593,Waylon Orchard,-21.0279,52675 Damon Heights,Rhode Island,"Waylon Orchard, Rhode Island"
4,38743,Buckinghamshire,karolann.org,41460,Wunsch Divide,-56.7542,06510 Jerde Village,Maine,"Wunsch Divide, Maine"
...,...,...,...,...,...,...,...,...,...
995,08036-7563,Bedfordshire,edmond.info,88156-2554,Moen Village,-24.3313,88945 Hortense Plaza,Georgia,"Moen Village, Georgia"
996,63660,Berkshire,genevieve.com,68079-6548,Magnolia Motorway,-50.1882,6989 Zena Walks,Wyoming,"Magnolia Motorway, Wyoming"
997,50921,Borders,lelah.net,63427,Nienow Park,14.5610,78912 Rogahn Hills,Missouri,"Nienow Park, Missouri"
998,56151,Cambridgeshire,ivy.biz,41172,Hickle Views,50.7896,2930 Murray Creek,Rhode Island,"Hickle Views, Rhode Island"
999,44594,Buckinghamshire,vilma.biz,80113-7668,Cathy Inlet,2.8125,3669 Kreiger Shores,Idaho,"Cathy Inlet, Idaho"

Handle missing data by filling NaN values with a specific value or using interpolation.

In [20]:
mean_of_sums = df.select_dtypes(include=['number']).sum().mean()
df = df.fillna(mean_of_sums)
df

,ZIP_CODE,COUNTY,DOMAIN_NAME,ZIP_CODE.1,STREET_NAME,LATITUDE,STREET_ADDRESS,STATE,FULL_ADDRESS
0,10108-9702,Borders,rosalyn.com,14649-0404,Riley Cliff,-21.2197,20530 Adaline Spurs,Georgia,"Riley Cliff, Georgia"
1,44432-2684,Berkshire,devin.info,13405,Johan Village,53.0743,9482 Sporer Keys,Maryland,"Johan Village, Maryland"
2,61808-2074,Bedfordshire,garret.name,56865-6328,Alanis Inlet,-28.6071,95859 Langosh Cliffs,Massachusetts,"Alanis Inlet, Massachusetts"
3,17550-8516,Bedfordshire,laverne.biz,52518-3593,Waylon Orchard,-21.0279,52675 Damon Heights,Rhode Island,"Waylon Orchard, Rhode Island"
4,38743,Buckinghamshire,karolann.org,41460,Wunsch Divide,-56.7542,06510 Jerde Village,Maine,"Wunsch Divide, Maine"
...,...,...,...,...,...,...,...,...,...
995,08036-7563,Bedfordshire,edmond.info,88156-2554,Moen Village,-24.3313,88945 Hortense Plaza,Georgia,"Moen Village, Georgia"
996,63660,Berkshire,genevieve.com,68079-6548,Magnolia Motorway,-50.1882,6989 Zena Walks,Wyoming,"Magnolia Motorway, Wyoming"
997,50921,Borders,lelah.net,63427,Nienow Park,14.5610,78912 Rogahn Hills,Missouri,"Nienow Park, Missouri"
998,56151,Cambridgeshire,ivy.biz,41172,Hickle Views,50.7896,2930 Murray Creek,Rhode Island,"Hickle Views, Rhode Island"
999,44594,Buckinghamshire,vilma.biz,80113-7668,Cathy Inlet,2.8125,3669 Kreiger Shores,Idaho,"Cathy Inlet, Idaho"

Export the DataFrame to a CSV file.

In [21]:
df.to_csv("/home/shuruyi/Documents/git/machine-learning/pandas/sample_file_export.csv")